name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v


      - name: Install Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libpng-dev libsamplerate0-dev
      - name: Build V
        run: make && ./v symlink -githubci
        
      - name: Build c2v and setup ~/code
        run: v install nedpals.vargs
        

