name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v


      - name: Install Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libpng-dev libsamplerate0-dev
      - name: Build V
        run: make && ./v symlink -githubci
        
      - name: Build c2v and setup ~/code
        run: |
          v install nedpals.vargs
          
      - name: Build c2v and setup ~/code
        run: |
          v install serkonda7.termtable
      - name: Build c2v and setup ~/code
        run: |
          v install etienne_napoleone.chalk
      - name: Checkout VFitNess
        uses: actions/checkout@v2
        with:
          path: VFitNess
      - name: Build c2v and setup ~/code
        run: |
         ls
         pwd
         cd ./VFitNess
         ls
         pwd
         v Src/Main.v || true
          
 
        

